#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
set -eu
LC_ALL=C
trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 15
echo "$BASHPID" > /run/$(basename $0).pid
source /usr/bin/variables
if ! [[ -d /lib/live/mount/rootfs ]]; then
	"$errores" --text="Este programa no puede ejecutarse desde una instalacion en un disco duro."
	exit 1
else
	donde="/mnt/miusb"
	"$miyad" --timeout=5 --title="Notificacion" --text="Este procedimiento activara la persistencia para el directorio /home; La memoria usb solo debe contener la particion del sistema operativo."
	dispositivo=$(fdisk -l | grep "Disco" | grep -v "loop" | grep -v "zram" | awk '{print $2}' | sed 's/.$//g' | yad --center --no-click --list --title="Seleccione dispositivo" --text="Seleccione el dispositivo donde copio el contenido de la imagen iso." --separator="" --column 'Dispositivo' --height 380 --width 150 --button="ACEPTAR":0)
	dispositivo2=$(echo $dispositivo"1")
	primero=$(fdisk -l | grep "$dispositivo2" | awk '{print $4}' | grep -v "GiB,")
	segundo=$(("$primero"+1))
	parted -a optimal -s "$dispositivo" -- mkpart primary ext4 $(echo $segundo"s") 100%
	dispositivo3=$(fdisk -l | grep "$dispositivo" | grep -v "loop" | grep -v "zram" | grep -v "Disco" | grep -v "Hidden" | awk '{print $1}' | grep -v "$dispositivo2")
	mkfs.ext4 -FFL persistence "$dispositivo3"
	mkdir -p "$donde"
	mount -t ext4 "$dispositivo3" "$donde"
	echo "/home union" > "$donde"/persistence.conf
	dd if=/dev/zero of="$donde"/swapfile.swp bs=1024 count=102400
	chown root:root "$donde"/swapfile.swp
	chmod 0600 "$donde"/swapfile.swp
	mkswap "$donde"/swapfile.swp
	umount -fl "$donde"
	"$final" --text="Reinicie su sistema para activar la persistencia."
	lxde-logout
fi
rm -f /run/$(basename $0).pid
exit 0
